redactions:
  "firstName": "md5"
  "lastName": "md5"
  "gender": "drop"
  "houseNumber": "redact"
  "street": "redact"
  "phone": "redact"
  "email": "redactEmailUsername"
  "latitude": "redactLocation"
  "longitude": "redactLocation"