redactors:
  - name: "redact"
    config:
      function: "replace"
      replacement: "REDACTED"
  - name: "redactEmailUsername"
    config:
      function: "replaceBeforeSeparator"
      replacement: "redacted"
      separator: "@"
  - name: "redactLocation"
    config:
      function: "truncateFloat64"
      decimals: 1

redactions:
  "firstName": "redact"
  "lastName": "redact"
  "gender": "redact"
  "houseNumber": "redact"
  "street": "redact"
  "phone": "redact"
  "email": "redactEmailUsername"
  "latitude": "redactLocation"
  "longitude": "redactLocation"